# Generated by Django 3.0.3 on 2020-03-03 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default='2b44d4b35d1611ea98bbacd1b8d2566c', editable=False, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='轮播图标题')),
                ('file', models.FileField(upload_to='', verbose_name='图片')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('index', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='顺序')),
                ('external_url', models.CharField(max_length=255, null=True, verbose_name='外链地址URL')),
            ],
            options={
                'verbose_name': '轮播图',
                'db_table': 'db_banner',
            },
        ),
    ]
