# Generated by Django 3.0.3 on 2020-03-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20200303_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.UUIDField(default='945bd3c25d2911ea9d9dacd1b8d2566c', editable=False, primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='顺序'),
        ),
    ]
