# Generated by Django 3.0.3 on 2020-03-05 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20200303_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
    ]
