# Generated by Django 3.0.3 on 2020-03-05 14:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('title', models.CharField(max_length=10, verbose_name='分类名称')),
                ('index', models.PositiveSmallIntegerField(default=0, verbose_name='顺序')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'db_table': 'db_classify',
            },
        ),
    ]
